
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async detectAndConvertToUtf8(bytes: number[]) : Promise<Result<ConvertedTextDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_and_convert_to_utf8", { bytes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async convertUtf8ToEncoding(text: string, targetEncoding: string) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("convert_utf8_to_encoding", { text, targetEncoding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFileChunkNative(filePath: string, offset: number, chunkSize: number) : Promise<Result<ChunkResultDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file_chunk_native", { filePath, offset, chunkSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async indexDocumentsNative(docs: DocSearchInput[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("index_documents_native", { docs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchDocumentsNative(query: string) : Promise<Result<SearchHitDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_documents_native", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async batchConvertFilesNative(items: BatchConvertItem[]) : Promise<Result<BatchConvertResultDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_convert_files_native", { items }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async computeTextDiffNative(oldText: string, newText: string) : Promise<Result<DiffChangeDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compute_text_diff_native", { oldText, newText }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async parseMarkdownNative(markdown: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_markdown_native", { markdown }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generatePdfNative(title: string, content: string) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_pdf_native", { title, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async highlightCodeNative(code: string, language: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlight_code_native", { code, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFileNative(filePath: string) : Promise<Result<ConvertedTextDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file_native", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * バッチ文字コード一括変換の指定項目 DTO
 */
export type BatchConvertItem = { 
/**
 * 対象ファイルパス
 */
file_path: string; 
/**
 * 変換先ターゲット文字コード ("UTF-8", "Shift_JIS")
 */
target_encoding: string }
/**
 * バッチ文字コード一括変換の全体実行結果 DTO
 */
export type BatchConvertResultDto = { 
/**
 * 変換成功ファイル数
 */
success_count: number; 
/**
 * 変換失敗ファイル数
 */
failure_count: number; 
/**
 * 実行ログ・メッセージ一覧
 */
messages: string[] }
/**
 * チャンク読み込み結果を表す DTO
 */
export type ChunkResultDto = { 
/**
 * 読み込まれたテキストチャンクデータ
 */
content: string; 
/**
 * 残りのファイルデータが存在するかどうか
 */
has_more: boolean; 
/**
 * ファイルの総バイトサイズ
 */
total_size: number }
/**
 * 文字コード変換結果を表す DTO
 */
export type ConvertedTextDto = { 
/**
 * 変換後の UTF-8 テキスト
 */
text: string; 
/**
 * 判定された元の文字コード名 ("UTF-8", "Shift_JIS", "EUC-JP")
 */
encoding: string }
/**
 * テキスト Diff 差分変更単位を表す DTO
 */
export type DiffChangeDto = { 
/**
 * 変更種別 ("insert", "delete", "equal")
 */
tag: string; 
/**
 * 変更行テキスト
 */
value: string; 
/**
 * 旧ドキュメントでの行番号 (1-indexed)
 */
old_line: number | null; 
/**
 * 新ドキュメントでの行番号 (1-indexed)
 */
new_line: number | null }
/**
 * インデックス検索の入力ドキュメント構造体
 */
export type DocSearchInput = { 
/**
 * ドキュメント識別子 ID
 */
id: string; 
/**
 * ドキュメントタイトル
 */
title: string; 
/**
 * ドキュメント本文およびタグテキスト
 */
content: string }
/**
 * 全文検索ヒット結果を表す DTO
 */
export type SearchHitDto = { 
/**
 * ヒットしたドキュメント ID
 */
doc_id: string; 
/**
 * ヒットしたドキュメントタイトル
 */
doc_title: string; 
/**
 * ヒットした行番号 (1-indexed)
 */
line_number: number; 
/**
 * ヒットした行のテキスト文字列
 */
line_text: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
